
package me.Source.LinkMe.Commands;

import me.Source.LinkMe.Linkme;
import org.bukkit.ChatColor;

public class Strings {
public static final String MSG_NO_PERMS = ChatColor.RED + "You do not have permission to use this command.";
public static String Announcer = Linkme.config.getString("announcer");
public static String Donatordescription = Linkme.config.getString("Donator.info.description");
public static String Donatorurl = Linkme.config.getString("Donator.info.url");
public static String Donatorstatus = Linkme.config.getString("Donator.info.enabled");
public static String Facebookdescription = Linkme.config.getString("Facebook.info.description");
public static String Facebookurl = Linkme.config.getString("Facebook.info.url");
public static String FacebookStatus = Linkme.config.getString("Facebook.info.enabled");
public static String Forumdescription = Linkme.config.getString("Forums.info.description");
public static String Forumurl = Linkme.config.getString("Forums.info.url");
public static String ForumStatus = Linkme.config.getString("Forums.info.enabled");
public static String Mumbledescription = Linkme.config.getString("Mumble.info.description");
public static String Mumbleip = Linkme.config.getString("Mumble.info.ip");
public static String MumbleStatus = Linkme.config.getString("Mumble.info.enabled");
public static String Rankdescription = Linkme.config.getString("RankingUp.info.description");
public static String RankupStatus = Linkme.config.getString("RankingUp.info.enabled");
public static String TS33description = Linkme.config.getString("Teamspeak3.info.description");
public static String TS3ip = Linkme.config.getString("Teamspeak3.info.ip");
public static String TS3Status = Linkme.config.getString("Teamspeak3.info.enabled");
public static String Twitchdescription = Linkme.config.getString("Twitch.info.description");
public static String Twitchurl = Linkme.config.getString("Twitch.info.url");
public static String TwitchStatus = Linkme.config.getString("Website.info.enabled");
public static String Twitterdescription = Linkme.config.getString("Twitter.info.description");
public static String Twitterurl = Linkme.config.getString("Twitter.info.url");
public static String TwitterStatus = Linkme.config.getString("Twitter.info.enabled");
public static String VentriloStatus = Linkme.config.getString("Ventrillo.info.enabled");   
public static String Ventdescription = Linkme.config.getString("Ventrillo.info.description");
public static String Ventip = Linkme.config.getString("Ventrillo.info.ip");
public static String StaffInfo1Enable = Linkme.config.getString("Staff-Info1.enable");
public static String StaffInfo1Title = Linkme.config.getString("Staff-Info1.title");
public static String StaffInfo1Name = Linkme.config.getString("Staff-Info1.name");
public static String StaffInfo1Facebook = Linkme.config.getString("Staff-Info1.facebook");
public static String StaffInfo1Twitter = Linkme.config.getString("Staff-Info1.twitter");
public static String StaffInfo2Enable = Linkme.config.getString("Staff-Info2.enable");
public static String StaffInfo2Title = Linkme.config.getString("Staff-Info2.title");
public static String StaffInfo2Name = Linkme.config.getString("Staff-Info2.name");
public static String StaffInfo2Facebook = Linkme.config.getString("Staff-Info2.facebook");
public static String StaffInfo2Twitter = Linkme.config.getString("Staff-Info2.twitter");
public static String StaffInfo3Enable = Linkme.config.getString("Staff-Info3.enable");
public static String StaffInfo3Title = Linkme.config.getString("Staff-Info3.title");
public static String StaffInfo3Name = Linkme.config.getString("Staff-Info3.name");
public static String StaffInfo3Facebook = Linkme.config.getString("Staff-Info3.facebook");
public static String StaffInfo3Twitter = Linkme.config.getString("Staff-Info3.twitter");
public static String Voicelist = Linkme.config.getString("VoiceList.info.description");
public static String Vote01Status = Linkme.config.getString("Vote.VoteLink01.description");
public static String Vote01description = Linkme.config.getString("Vote.VoteLink01.enabled");
public static String Vote01url = Linkme.config.getString("Vote.VoteLink01.url");
public static String Vote02Status = Linkme.config.getString("Vote.VoteLink01.description");
public static String Vote02description = Linkme.config.getString("Vote.VoteLink01.enabled");
public static String Vote02url = Linkme.config.getString("Vote.VoteLink01.url");
public static String Vote03Status = Linkme.config.getString("Vote.VoteLink01.description");
public static String Vote03description = Linkme.config.getString("Vote.VoteLink01.enabled");
public static String Vote03url = Linkme.config.getString("Vote.VoteLink01.url");
public static String Vote04Status = Linkme.config.getString("Vote.VoteLink01.description");
public static String Vote04description = Linkme.config.getString("Vote.VoteLink01.enabled");
public static String Vote04url = Linkme.config.getString("Vote.VoteLink01.url");
public static String Vote05Status = Linkme.config.getString("Vote.VoteLink01.description");
public static String Vote05description = Linkme.config.getString("Vote.VoteLink01.enabled");
public static String Vote05url = Linkme.config.getString("Vote.VoteLink01.url");
public static String Vote06Status = Linkme.config.getString("Vote.VoteLink01.description");
public static String Vote06description = Linkme.config.getString("Vote.VoteLink01.enabled");
public static String Vote06url = Linkme.config.getString("Vote.VoteLink01.url");
public static String Vote07Status = Linkme.config.getString("Vote.VoteLink01.description");
public static String Vote07description = Linkme.config.getString("Vote.VoteLink01.enabled");
public static String Vote07url = Linkme.config.getString("Vote.VoteLink01.url");
public static String Vote08Status = Linkme.config.getString("Vote.VoteLink01.description");
public static String Vote08description = Linkme.config.getString("Vote.VoteLink01.enabled");
public static String Vote08url = Linkme.config.getString("Vote.VoteLink01.url");
public static String Vote09Status = Linkme.config.getString("Vote.VoteLink01.description");
public static String Vote09description = Linkme.config.getString("Vote.VoteLink01.enabled");
public static String Vote09url = Linkme.config.getString("Vote.VoteLink01.url");
public static String Vote10Status = Linkme.config.getString("Vote.VoteLink01.description");
public static String Vote10description = Linkme.config.getString("Vote.VoteLink01.enabled");
public static String Vote10url = Linkme.config.getString("Vote.VoteLink01.url");
public static String Websitedescription = Linkme.config.getString("Website.info.description");
public static String Websiteurl = Linkme.config.getString("Website.info.url");
public static String WebsiteStatus = Linkme.config.getString("Voting.info.enabled");
public static String Youtubedescription = Linkme.config.getString("Youtube.info.description");
public static String Youtubeurl = Linkme.config.getString("Youtube.info.url");
public static String YoutubeStatus = Linkme.config.getString("Youtube.info.enabled");
}