#########################
####  LINK-ME V2.7.2    ###
#########################



###################
# GLOBAL SETTINGS #
###################

## Change the name of the announcer here this is global and will show in every command
announcer: '[LinkMe]'
nopermission: 'Sorry you do not have permission to do this, please contact your system adminstrator'

#####################################
# FEATURES BELOW ARE IN DEVELOPMENT #
#####################################

###################
# MySQL SETTINGS  #
###################

Hostname: ''
Port: '3306'  
# Dont change the port unless you know the shit your messing with
Database: ''
Username: ''
Password: ''

##################
# PANEL SETTINGS #
##################

# API Access
panel_api_key: ''
panel_url: 'http://www.yoursite.com/panel/api/api.php'
#Include everything up to where the API Is actually needed to add.

# END OF CONFIG
