#########################
####  LINK-ME V2.6    ###
#########################


# If you would like a list of the comptabile colour codes please visit 
# http://minecraft.gamepedia.com/Formatting_codes#Color_codes


###################
# GLOBAL SETTINGS #
###################

## Change the name of the announcer here this is global and will show in every command
announcer: '[LinkMe]'

# END OF CONFIG