#########################
####  LINK-ME V2.4    ###
#########################


announcer: '[LinkMe]'
# Donator
Donator: 
    info:
        enabled: true
        description: 'Go have a look and check out our donation page at and remember every donation keeps the server running.'
        url: 'http://www.google.com'
# Facebook
Facebook:
    info:
        enabled: true
        description: 'Come visit our Ventrillo server at'
        url: 'http://www.google.com'
# Forum
Forums:
    info:
        enabled: true
        description: 'Come visit our Forums at'
        url: 'http://www.google.com'
# Mumble
Mumble:
    info:
        enabled: true
        description: 'Come visit our Mumble server at'
        ip: '127.0.0.1:9999'
# Ranking Up
RankingUp:
    info:
        enabled: true
        description: 'Rank up information here' 
# Teamspeak 3
Teamspeak3:
    info:
        enabled: true
        description: 'Come visit our Teamspeak 3 server at'
        ip: 'http://www.google.com'
# Twitch 
Twitch:
    info:
        enabled: true
        description: 'Come visit our Ventrillo server at'
        url: 'http://www.google.com'
# Twitter
Twitter:
    info:
        enabled: true
        description: 'Come visit our Ventrillo server at'
        url: 'http://www.google.com'
# Ventrillo
Ventrillo:
    info:
        enabled: true
        description: 'Come visit our Ventrillo server at'
        ip: '127.0.0.1:9999'
# VoiceList
VoiceList:
    info:
        description: 'This is a list of our Voice Servers'
# Voting
Voting:
    info:
        enabled: true
        description: 'Come visit our Ventrillo server at'
        url: 'http://www.google.com'
# Website
Website:
    info:
        enabled: true
        description: 'Come visit our Website at'
        url: 'http://www.google.com'
Youtube:
    info:
        enabled: true
        description: 'You can find out Youtube page at'
        url: 'http://www.youtube.com'
# END OF CONFIG