name: Link-Me
main: Me.RyanWild.Kyled1986.LinkMe.Linkme
version: 2.7.2
description: Link Me

commands:
  site:
    description: Site website
  forum:
    description: Forums
  bforum:
    description: Broadcast forums
  bsite:
    description: Broadcast site website
  mum:
    description: Mumble Server address
  ts:
    description: TS3 IP
  twitch:
    description: Twitch Steam
  btwitch:
    description: Broadcast Twitch Steam
  vent:
    description: vent IP
  facebook:
    description: Facebook Page
  bfacebook:
    description: Broadcast Facebook Page
  youtube:
    description: Youtube Page
  byoutube:
    description: Broadcast Youtube Page
  twitter:
    description: Twitter Url 
  btwitter:
    description: Broadcast Twitter Url
  donator:
    description: Donation Page
  bdonator:
    description: Broadcast Donation Page
  bvoice:
    description: Broadcasts all voice servers
  lmreload:
    description: Reloads LinkMe
  vote:
    description: Displays Voting information and URL
  rankup:
    description: Displays all the information about how to rank up and includes a link
  brankup:
    description: Broadcasts all the information about how to rank up and includes a link
  staffrank1:
    description: Broadcasts all the information about how to rank up and includes a link
  staffrank2:
    description: Broadcasts all the information about how to rank up and includes a link
  staffrank3:
    description: Broadcasts all the information about how to rank up and includes a link