name: LinkMe
main: me.RyanWild.LinkMe.Linkme
dev-url: http://dev.bukkit.org/bukkit-plugins/linkme/
version: 2.2
description: Link Me

commands:
  site:
    description: Site website
  forum:
    description: Forums
  bforum:
    description: Broadcast forums
  bsite:
    description: Broadcast site website
  mum:
    description: Mumble Server address
  linkme:
    description: List all commands
  lm:
    description: List all commands
  ts:
    description: TS3 IP
  vent:
    description: vent IP
  facebook:
    description: Facebook Page
  bfacebook:
    description: Broadcast Facebook Page
  youtube:
    description: Youtube Page
  byoutube:
    description: Broadcast Youtube Page
  twitter:
    description: Twitter Url 
  btwitter:
    description: Broadcast Twitter Url
  donator:
    description: Donation Page
  bdonator:
    description: Broadcast Donation Page
  bvoice:
    description: Broadcasts all voice servers
  lmreload:
    description: Reloads LinkMe
  vote:
    description: Displays Voting information and URL
  bvote:
    description: Broadcasts the Vote information
  rankup:
    description: Displays all the information about how to rank up and includes a link
  brankup:
    description: Broadcasts all the information about how to rank up and includes a link