name: Link-Me
main: Me.RyanWild.Kyled1986.LinkMe.Linkme
version: 2.7.4
description: Link Me

commands:
  bdonator:
    description: Broadcast Donation Page
  bfacebook:
    description: Broadcast Facebook Page
  bforum:
    description: Broadcast forums
  brankup:
    description: Broadcasts all the information about how to rank up and includes a link
  bsite:
    description: Broadcast site website
  btwitch:
    description: Broadcast Twitch Steam
  btwitter:
    description: Broadcast Twitter Url
  bvoice:
    description: Broadcasts all voice servers
  byoutube:
    description: Broadcast Youtube Page
  donator:
    description: Donation Page
  facebook:
    description: Facebook Page
  forum:
    description: Forums
  lmreload:
    description: Reloads LinkMe
  rankup:
    description: Displays all the information about how to rank up and includes a link
  mum:
    description: Mumble Server address
  set:
    description: sets text in game DEVELOPMENT!
  site:
    description: Site website
  ts:
    description: TS3 IP
  twitch:
    description: Twitch Steam
  twitter:
    description: Twitter Url 
  vent:
    description: vent IP
  youtube:
    description: Youtube Page
  vote:
    description: Displays Voting information and URL