name: Link-Me
main: me.Source.LinkMe.Linkme
version: 2.5
description: Link Me

commands:
  site:
    description: Site website
  forum:
    description: Forums
  bforum:
    description: Broadcast forums
  bsite:
    description: Broadcast site website
  mum:
    description: Mumble Server address
  ts:
    description: TS3 IP
  twitch:
    description: Twitch Steam
  btwitch:
    description: Broadcast Twitch Steam
  vent:
    description: vent IP
  facebook:
    description: Facebook Page
  bfacebook:
    description: Broadcast Facebook Page
  youtube:
    description: Youtube Page
  byoutube:
    description: Broadcast Youtube Page
  twitter:
    description: Twitter Url 
  btwitter:
    description: Broadcast Twitter Url
  donator:
    description: Donation Page
  bdonator:
    description: Broadcast Donation Page
  bvoice:
    description: Broadcasts all voice servers
  lmreload:
    description: Reloads LinkMe
  vl1:
    description: Displays Voting information and URL
  vl2:
    description: Displays Voting information and URL
  vl3:
    description: Displays Voting information and URL
  vl4:
    description: Displays Voting information and URL
  vl5:
    description: Displays Voting information and URL
  vl6:
    description: Displays Voting information and URL
  vl7:
    description: Displays Voting information and URL
  vl8:
    description: Displays Voting information and URL
  vl9:
    description: Displays Voting information and URL
  vl10:
    description: Displays Voting information and URL
  rankup:
    description: Displays all the information about how to rank up and includes a link
  brankup:
    description: Broadcasts all the information about how to rank up and includes a link